events {}
http {
    server {
        listen 80;
        server_name quotewear.store www.quotewear.store admin.quotewear.store;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name quotewear.store www.quotewear.store;

        ssl_certificate /etc/letsencrypt/live/quotewear.store/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/quotewear.store/privkey.pem;

        location / {
            resolver 127.0.0.11 valid=30s;
            set $upstream http://storefront:8000;
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }

    server {
        listen 443 ssl;
        server_name admin.quotewear.store;

        ssl_certificate /etc/letsencrypt/live/quotewear.store/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/quotewear.store/privkey.pem;

        location / {
            resolver 127.0.0.11 valid=30s;
            set $upstream http://backend:9000;
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}
